# Generated by Django 2.0.5 on 2018-05-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='title',
            field=models.CharField(default='occupation', max_length=200),
            preserve_default=False,
        ),
    ]
