# Generated by Django 2.0.5 on 2018-05-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180527_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
